# bulk push whole repo to EC2 instance serving the application

start:
	aws ec2 start-instances --instance-ids i-07f811e984fc90a3b

stop:
	aws ec2 stop-instances --instance-ids i-07f811e984fc90a3b

ech:
	echo 'heee'
